/** @type {import('tailwindcss').Config} */
export default {
  darkMode: 'class',
  content: ['./index.html', './src/**/*.{ts,tsx}'],
  theme: {
    extend: {
      colors: {
        secondary: '#006b59',
        'surface-container-low': '#f3f4f6',
        'on-error': '#ffffff',
        'surface-container-highest': '#e1e2e4',
        background: '#f8f9fb',
        surface: '#f8f9fb',
        'on-primary-container': '#c4d2ff',
        'primary-fixed-dim': '#b2c5ff',
        primary: '#003d9b',
        'secondary-container': '#7cf8da',
        'primary-container': '#0052cc',
        'tertiary-fixed': '#dae2ff',
        outline: '#737685',
        tertiary: '#29417c',
        'on-surface-variant': '#434654',
        'on-tertiary-fixed': '#001849',
        'surface-container-lowest': '#ffffff',
        'surface-container': '#edeef0',
        'inverse-surface': '#2e3132',
        'surface-dim': '#d9dadc',
        'inverse-on-surface': '#f0f1f3',
        'surface-bright': '#f8f9fb',
        'outline-variant': '#c3c6d6',
        'tertiary-container': '#425995',
        'on-primary-fixed': '#001848',
        'secondary-fixed': '#7cf8da',
        error: '#ba1a1a',
        'tertiary-fixed-dim': '#b2c5ff',
        'inverse-primary': '#b2c5ff',
        'on-tertiary-fixed-variant': '#2d447f',
        'on-primary': '#ffffff',
        'surface-tint': '#0c56d0',
        'on-secondary-fixed-variant': '#005143',
        'on-background': '#191c1e',
        'primary-fixed': '#dae2ff',
        'on-tertiary-container': '#c5d2ff',
        'on-surface': '#191c1e',
        'secondary-fixed-dim': '#5ddbbe',
        'on-secondary-container': '#00725f',
        'error-container': '#ffdad6',
        'on-primary-fixed-variant': '#0040a2',
        'on-secondary-fixed': '#00201a',
        'on-error-container': '#93000a',
        'surface-variant': '#e1e2e4',
        'surface-container-high': '#e7e8ea',
        'on-tertiary': '#ffffff',
        'on-secondary': '#ffffff',
      },
      fontFamily: {
        headline: ['Manrope', 'system-ui', 'Segoe UI', 'sans-serif'],
        body: ['Inter', 'system-ui', 'Segoe UI', 'sans-serif'],
        label: ['Inter', 'system-ui', 'Segoe UI', 'sans-serif'],
      },
      borderRadius: {
        DEFAULT: '0.125rem',
        lg: '0.25rem',
        xl: '0.5rem',
        full: '0.75rem',
      },
    },
  },
  plugins: [],
}

